# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: jobmarketplace-mongo
    volumes:
      - mongo-data:/data/db

  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb

  users-service:
    build:
      context: .
      dockerfile: ./apps/users-service/Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    env_file:
      - .env
    depends_on:
      - auth-service
      - users-service

volumes:
  mongo-data:
